### PR TITLE
RC-37: Add ability to change application name via global property

### PR DESCRIPTION
**Pull request by corneliouzbett**

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@corneliouzbett   Thanks for  working on this,you can also checkout this to make a better pr https://wiki.openmrs.org/display/docs/Pull+Request+Tips

**Comment by dkayiwa** [comment]
@corneliouzbett are you still interested in this?

**Comment by corneliouzbett** [comment]
> @corneliouzbett are you still interested in this?

Hello @dkayiwa!
Not really. At the time I was setting up the registration core module in our instance, I couldn't retrieve the runtime properties because it was looking for `openmrs-runtime.properties` but for our implementation its `amrs-runtime.properties`. So I think it's worth having this.

**Comment by dkayiwa** [comment]
@corneliouzbett do you wanna create the corresponding ticket?

**Comment by corneliouzbett** [comment]
> @corneliouzbett do you wanna create the corresponding ticket?

@dkayiwa ticket created. [here](https://issues.openmrs.org/browse/RC-37)

**Comment by dkayiwa** [comment]
Thanks @corneliouzbett 
I just made it ready for work. Feel free to claim it.

**Comment by corneliouzbett** [comment]
Closing in favor of #26

**Pull request closed without merging**
