### PR TITLE
RA-1086 - Saving patient identifiers that are manually entered 

### PR DESCRIPTION
**Pull request by ssmusoke**
This is a first attempt at a working solution to save manually entered preferred identifiers which do not conform to the Luhn algorithm validator based on identifier generator sources.

Need to view downstream impacts of the change as I am not aware of design choices and implications of the change

### CODE REVIEW

**Comment by dkayiwa** [comment]
@ssmusoke if you do not want the Luhn algorithm validator, why don't you just remove it from the identifier type as configured in the user interface?

**Comment by ssmusoke** [comment]
The default identifier source generator available is based on the Luhn
generator.

The existing code validates any manually entered identifier value against
an existing id generation source  irrespective of whether the manually
entered preferred identifier  uses it or not.

**Comment by dkayiwa** [comment]
Do you think you can create a test for this?

**Comment by dkayiwa** [comment]
@ssmusoke  did you give up on this? :)

**Comment by ssmusoke** [comment]
Daniel,

We were forced to remove the capture of an additional identifier at
registration as a temporary hack for our needs. I will get back to this at
a later date

Stephen

Stephen S. Musoke
Skype: ssmusoke
Twitter: @ssmusoke
+256 776 553 260
http://ssmusoke.com
*Our deepest fear is not that we are inadequate. Our deepest fear is that
we are powerful beyond measure ~Marianne Williamson*

**Comment by dkayiwa** [comment]
Closing this for now. Feel free to reopen when you regain interest in it. :)

**Pull request closed without merging**
